name: Run Docker Container

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  run_docker_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run fido binaries container
      uses: docker://guarddogai/binaries:1.1.1
      with:
        args: -it --name binaries_01
