name: Build Binaries for prod

on:
  push:
    branches:
      - main 

jobs:
  run_docker_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    
    - name: Build Binaries for vfido
      uses: docker://guarddogai/binaries:1.1.1
      with:
        args: docker_binaries_dev -it --name binaries 
        
        
